name: Native Test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Update apt packages
        if: startsWith(matrix.os,'ubuntu')
        run: sudo apt-get update
      - name: Install Curl
        if: startsWith(matrix.os,'ubuntu')
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Native Test
        env:
          JIRA_USERNAME: ${{secrets.JIRA_USERNAME}}
          JIRA_API_TOKEN: ${{secrets.JIRA_API_TOKEN}}
        run: ./gradlew hostOSNativeTest