name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    environment: Release
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Update apt packages
        if: startsWith(matrix.os,'ubuntu')
        run: sudo apt-get update

      - name: Install Curl
        if: startsWith(matrix.os,'ubuntu')
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Maven Central Publish
        env:
          OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
          ORG_GRADLE_PROJECT_signingKeyId: ${{secrets.ORG_GRADLE_PROJECT_signingKeyId}}
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.ORG_GRADLE_PROJECT_signingKey}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.ORG_GRADLE_PROJECT_signingPassword}}
          IS_MAIN_PUBLISHER: ${{ startsWith(matrix.os,'ubuntu') }}
          TIX_VERSION: ${{github.ref_name}}
        run: ./gradlew publishAllPublicationsToSonatypeRepository

      - name: Get version information
        id: version
        uses: ncipollo/semantic-version-action@v1

      - name: Generate release diff
        env:
          BEGIN_COMMIT: ${{ steps.version.outputs.previous_tag }}
          END_COMMIT: ${{ steps.version.outputs.tag }}
        run: git log --all --graph --oneline ${BEGIN_COMMIT}..${END_COMMIT} > release_notes.txt

      - name: Github Publish
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: false
          bodyFile: release_notes.txt
          draft: true