name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: macos-latest
    environment: Release
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Central Publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{secrets.OSSRH_USERNAME}}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{secrets.OSSRH_PASSWORD}}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{secrets.ORG_GRADLE_PROJECT_signingKey}}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{secrets.ORG_GRADLE_PROJECT_signingPassword}}
          TIX_VERSION: ${{github.ref_name}}
        run: ./gradlew publishAllPublicationsToMavenCentralRepository
      - name: Github Publish
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          generateReleaseNotes: true